title:              SEC-WAVE
email:              
description:        AI-powered cybersecurity and comprehensive compliance
author:             
baseurl:            ""
url:                "https://Kaademos.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username: Sec-Wave

people:
- name: Olivia Martinez
  pic: 1
  position: Chief Data Scientist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Liam Patterson
  pic: 2
  position: Head of Business Intelligence
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sophia Nguyen
  pic: 3
  position: Lead Data Analyst
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

  - name: Sophiamfmf
  pic: 4
  position: Lead Data dndnd
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Add your google-analytics ID here to activate google analytics
google_analytics:    # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
